version: "3.7"

volumes:
  php_mysql:


networks:
  php_mysql_network:
    driver: bridge

services:
  nginx:
    image: nginx
    restart: always
    networks:
      - php_mysql_network
    ports:
      - "8080:80"
    volumes:
      - ./www:/var/www/html/
      - ./conf:/etc/nginx/conf.d
    links:
      - php

  php:
    image: php:7.3-fpm
    container_name: php-fpm
    networks:
      - php_mysql_network
    volumes:
      - ./www:/var/www/html/
    depends_on:
      - mysql_db

  mysql_db:
    image: mysql
    volumes:
      - php_mysql:/var/lib/mysql
    networks:
      - php_mysql_network
    ports:
      - 3308:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: shop
